controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_position_controller:
      type: position_controllers/JointGroupPositionController
      pid:
        p: 0.5
        d: 0.5
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

joint_position_controller:
  ros__parameters:
    joints:
      - Joint0
      - Joint1
      - Joint2
      - Joint3
      - Joint4
    interface_name: position
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
      - effort