controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController
      publish_topic: "/joint_trajectory_controller/commands"
      pid:
        p: 1.0
        i: 0.1
        d: 1
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

joint_trajectory_controller:
  ros__parameters:
    joints:
      - Joint0
      - Joint1
      - Joint2
      - Joint3
      - Joint4
    interface_name: position
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
